name: Inference Integration Test

on:
  workflow_dispatch:           # run manually
  schedule:                    # run every hour
    - cron: '*/30 * * * *'
  push:                        # run on every push
    branches: [main]

jobs:
  inference-integration:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy requests
        python -m pip install -e .

    - name: Run minimal inference
      env:
        INFERENCE_TOKEN: ${{ secrets.INFERENCE_TOKEN }}
        SQUEEZENET_MODEL_ID: ${{ secrets.SQUEEZENET_MODEL_ID }}
      run: |
        python -c "
        import numpy as np;
        from npucloud_client import inference
        x = np.random.randn(1, 3, 224, 224)
        model_id = '${SQUEEZENET_MODEL_ID}'
        token = '${INFERENCE_TOKEN}'
        output, profiling_info = inference(x, model_id, token)
        print('Output:', output.shape)
        print('Profiling:', profiling_info)
        "